namespace HighBar.Client

open System.Text

/// Generates Spring engine TDF-format startup scripts from EngineConfig.
module ScriptGenerator =

    /// Generate a complete Spring engine startup script for a two-team game.
    let generate (config: EngineConfig) : string =
        let ourFaction = config.OurSide.ToLowerInvariant()
        let opponentFaction = config.OpponentSide.ToLowerInvariant()
        let sb = StringBuilder()
        let ln (s: string) = sb.AppendLine(s) |> ignore
        let speed = config.GameSpeed

        ln "[GAME]"
        ln "{"
        ln $"\tGameType={config.GameType};"
        ln $"\tMapName={config.MapName};"
        ln "\tModHash=1;"
        ln "\tMapHash=1;"
        ln "\tIsHost=1;"
        ln "\tHostIP=127.0.0.1;"
        ln "\tHostPort=0;"
        ln "\tMyPlayerName=HighBarV2Test;"
        ln "\tNoHelperAIs=0;"
        ln "\tStartPosType=0;"
        ln "\tGameStartDelay=0;"
        ln "\tFixedRNGSeed=1;"
        ln ""
        ln "\t[MODOPTIONS]"
        ln "\t{"
        ln "\t\tGameMode=3;"
        ln "\t\tdraft_mode=disabled;"
        ln $"\t\tteamfaction_0={ourFaction};"
        ln $"\t\tteamfaction_1={opponentFaction};"
        ln $"\t\tMinSpeed={speed};"
        ln $"\t\tMaxSpeed={speed};"
        ln "\t\tdeathmode=neverend;"
        ln "\t\tdebugcommands=1:cheat|3:globallos;"
        ln "\t}"
        ln ""
        ln "\t[MAPOPTIONS]"
        ln "\t{"
        ln "\t}"
        ln ""
        ln "\t[PLAYER0]"
        ln "\t{"
        ln "\t\tName=HighBarV2Test;"
        ln "\t\tTeam=0;"
        ln "\t\tIsFromDemo=0;"
        ln "\t\tSpectator=1;"
        ln "\t}"
        ln ""
        ln "\t[AI0]"
        ln "\t{"
        ln "\t\tName=HighBarV2;"
        ln "\t\tTeam=0;"
        ln "\t\tShortName=HighBarV2;"
        ln "\t\tVersion=0.1;"
        ln "\t\tHost=0;"
        ln "\t\t[OPTIONS]"
        ln "\t\t{"
        ln $"\t\t\tsocket_path={config.SocketPath};"
        ln "\t\t}"
        ln "\t}"
        ln ""
        ln "\t[AI1]"
        ln "\t{"
        ln $"\t\tName={config.OpponentAI};"
        ln "\t\tTeam=1;"
        ln $"\t\tShortName={config.OpponentAI};"
        ln "\t\tVersion=0.1;"
        ln "\t\tHost=0;"
        ln "\t}"
        ln ""
        ln "\t[TEAM0]"
        ln "\t{"
        ln "\t\tTeamLeader=0;"
        ln "\t\tAllyTeam=0;"
        ln $"\t\tSide={config.OurSide};"
        ln "\t\tStartPosX=1536;"
        ln "\t\tStartPosZ=4096;"
        ln "\t}"
        ln ""
        ln "\t[TEAM1]"
        ln "\t{"
        ln "\t\tTeamLeader=0;"
        ln "\t\tAllyTeam=1;"
        ln $"\t\tSide={config.OpponentSide};"
        ln "\t\tStartPosX=4608;"
        ln "\t\tStartPosZ=4096;"
        ln "\t}"
        ln ""
        ln "\t[ALLYTEAM0]"
        ln "\t{"
        ln "\t\tNumAllies=0;"
        ln "\t}"
        ln ""
        ln "\t[ALLYTEAM1]"
        ln "\t{"
        ln "\t\tNumAllies=0;"
        ln "\t}"
        ln ""
        ln "\tNumTeams=2;"
        ln "\tNumAllyTeams=2;"
        ln "\tNumPlayers=1;"
        ln "}"

        sb.ToString()
